### ISSUE TITLE
http://blog.zorg.tk/nanoconverter/ is unreachable

### ISSUE THREAD

**Issue by ghost** [ZorgeR/nanoConverter#8]
@ZorgeR 
* http://blog.zorg.tk/nanoconverter/ is unreachable.....
* can you please look into it...

**Comment by ZorgeR** [comment]
Hi! Yeap, this site is not available. No need to recover. Just use this repo to get information about app.

**Comment by ghost** [comment]
updated as part in https://gitlab.com/fdroid/fdroiddata/-/merge_requests/13587
* thank you
